name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # adjust if you use a different Node version

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    # Uncomment this step if you add tests later
    # - name: Run tests
    #   run: npm run test

    - name: Build project
      run: npm run build
